
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeload.kubeload.efrat19.io
  resources:
  - loadmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeload.kubeload.efrat19.io
  resources:
  - loadmanagers/status
  verbs:
  - get
  - patch
  - update
