apiVersion: kubeload.kubeload.efrat19.io/v1
kind: LoadManager
metadata:
  name: loadmanager-sample
spec:
  # Add fields here
  foo: bar
  loadSetup:
    hatchRate: 1
    initialLoad: 2
    interval: 1m
    maxLoad: 8
  selector:
    matchLabels:
      app: spider
