name: Publish Kubeload
on: [push]
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: efrat19/kubeload
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "amd64-latest,amd64-${{ github.sha }}"
  build-arm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: efrat19/kubeload
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "arm-latest,arm-${{ github.sha }}"
  push-manifest:
    runs-on: [ubuntu-latest]
    needs:
#      - build-arm
      - build-amd64
    steps:
      - name: setup docker(Without version)
        uses: docker-practice/actions-setup-docker@master
      - run: |
          docker manifest create efrat19/kubeload:latest efrat19/kubeload:amd64-latest
          docker manifest create efrat19/kubeload:${{ github.sha }} efrat19/kubeload:amd64-${{ github.sha }}
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker manifest push efrat19/kubeload:latest
          docker manifest push efrat19/kubeload:${{ github.sha }}

